[package]
name = "unbound-tome"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [".", "web", "service", "entity", "migration"]

[dependencies]
unbound-tome-web = { path = "web" }