[package]
name = "unbound-tome"
version = "0.1.0"
edition = "2021"
publish = false
build = "build.rs"

[workspace]
members = [".", "web", "domains", "migration", "utils"]

[dependencies]
unbound-tome-web = { path = "web" }