[package]
name = "unbound-tome"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
members = [".", "web", "service", "domains", "migration", "utils"]

[dependencies]
unbound-tome-web = { path = "web" }
