services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: unboundtome
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: unbound_tome_development
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 

volumes:
  pgdata: