services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: loco
      POSTGRES_PASSWORD: loco
      POSTGRES_DB: myapp_development
    volumes:
      - pgdata:/var/lib/postgresql/data 
    ports:
      - 5432:5432
 

volumes:
  pgdata: